#If rake db:create not working try to gem uninstall pg and install pg again


development:
  adapter: postgresql
  encoding: unicode
  database: salesapp
  pool: 5
  username: postgres
  password: enter123
  host: localhost

test:
  adapter: postgresql
  encoding: unicode
  database: postgres
  pool: 5
  username: postgres
  password: enter123
  host: localhost

production:
  adapter: postgresql
  encoding: unicode
  database: postgres
  pool: 5
  username: postgres
  password: enter123
  host: localhost
  
#sslmode: disable